"""I/O utilities for the BCL scanner.

File discovery, encoding-tolerant reading, output writing with the AI-ENRICHED
incremental-protection guard. None of this logic is language-specific — it is
shared by every plugin.

The ``write()`` function honours a process-wide ``--force`` flag toggled via
:func:`set_force_overwrite`. The default is to skip files whose first 500
bytes contain the ``<!-- AI-ENRICHED -->`` marker.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Iterable


# ──────────────────────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────────────────────

# Directories we never recurse into.
IGNORE_DIRS = {
    ".git", ".idea", ".gradle", ".mvn", "target", "build", "out", "node_modules",
    ".code2wiki", ".vscode", ".settings",
    "logs", "log", "tmp", "dist", "coverage",
}

# Project file suffixes recognised by the legacy Java pipeline. Other plugins
# define their own suffix sets locally and use these as a fallback when their
# scanner walks the project tree.
JAVA_SUFFIXES = {".java", ".kt", ".groovy"}
CONFIG_SUFFIXES = {".yml", ".yaml", ".properties", ".xml"}
SQL_SUFFIXES = {".sql"}

# Auxiliary knowledge sources (Claude / Cursor / Agents memory directories).
# These contribute optional context to ``06_auxiliary_knowledge/`` but never
# the primary source of truth for the BCL.
AUXILIARY_DIRS = {
    ".claude": "Claude/人工技能或记忆",
    ".cursor": "Cursor rules/上下文",
    ".agents": "Agents/skills/记忆",
}
AUXILIARY_SUFFIXES = {".md", ".mdc", ".txt", ".yaml", ".yml", ".json"}

# Output markers
AI_ENRICHED_MARKER = "<!-- AI-ENRICHED -->"
SCANNER_MARKER = "<!-- GENERATED BY AUTO-WIKI SCANNER -->"
# Files that ALWAYS overwrite on subsequent runs — pure machine indexes that
# carry no human-curated content.
ALWAYS_OVERWRITE = {"inventory.json", "generation_report.md", "domain_merge_log.md"}

# Module-level toggle controlled by --force. Use :func:`set_force_overwrite`
# rather than touching this directly so callers stay decoupled from the
# module's internal state.
_force_overwrite = False


# Generic "string literal" regex used by string-value extractors across
# plugins. Kept here because both the Java analyzer and the writer fall back
# on it for annotation arg parsing.
STRING_RE = re.compile(r'"([^"]+)"')


def set_force_overwrite(value: bool) -> None:
    """Toggle the global ``--force`` flag.

    When true, ``write()`` overwrites files even when they carry the
    AI-ENRICHED marker. Defaults to false at module load.
    """
    global _force_overwrite
    _force_overwrite = bool(value)


# ──────────────────────────────────────────────────────────────────────────────
# File reading
# ──────────────────────────────────────────────────────────────────────────────

def read_text(path: Path, limit: int = 300_000) -> str:
    """Read a file with graceful encoding fallback.

    Tries UTF-8 (with and without BOM), GB18030 (common in legacy Chinese
    codebases), and Latin-1 in that order. Returns the empty string on
    OSError. Truncates at ``limit`` bytes so we never thrash on accidentally
    huge files.
    """
    try:
        data = path.read_bytes()
    except OSError:
        return ""
    if len(data) > limit:
        data = data[:limit]
    for encoding in ("utf-8", "utf-8-sig", "gb18030", "latin-1"):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("utf-8", errors="ignore")


def iter_files(root: Path, max_files: int) -> Iterable[Path]:
    """Yield up to ``max_files`` files under ``root``, skipping IGNORE_DIRS
    and dot-prefixed directories."""
    count = 0
    for current_root, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS and not d.startswith(".")]
        for file_name in files:
            if count >= max_files:
                return
            path = Path(current_root) / file_name
            if path.is_file():
                count += 1
                yield path


def iter_auxiliary_files(root: Path, max_files: int = 300) -> Iterable[Path]:
    """Yield optional knowledge files under ``.claude/`` / ``.cursor/`` /
    ``.agents/`` directories. Capped at ``max_files`` so a misconfigured
    project does not flood the BCL with stale notes."""
    count = 0
    for dirname in AUXILIARY_DIRS:
        base = root / dirname
        if not base.exists() or not base.is_dir():
            continue
        for current_root, dirs, files in os.walk(base):
            dirs[:] = [d for d in dirs if d not in {"node_modules", "target", "build", ".git"}]
            for file_name in files:
                if count >= max_files:
                    return
                path = Path(current_root) / file_name
                if path.is_file() and path.suffix.lower() in AUXILIARY_SUFFIXES:
                    count += 1
                    yield path


def rel(path: Path, root: Path) -> str:
    """Return ``path`` relative to ``root`` as a POSIX-style string."""
    return path.relative_to(root).as_posix()


def first_match(pattern: re.Pattern[str], text: str) -> str | None:
    """Return the first capture group of the first ``pattern`` match, or None."""
    match = pattern.search(text)
    return match.group(1) if match else None


def extract_string_values(raw: str) -> list[str]:
    """Return every ``"..."`` string literal in ``raw``, skipping Spring
    placeholders like ``${api.prefix}``.

    Used to pull path arrays out of Spring annotations like
    ``@RequestMapping(path = ["/a", "/b"])`` — the regex captures both
    strings because it greps the entire annotation arg block.
    """
    values = STRING_RE.findall(raw or "")
    return [v for v in values if v and not v.startswith("${")]


# ──────────────────────────────────────────────────────────────────────────────
# Output writing
# ──────────────────────────────────────────────────────────────────────────────

def write(path: Path, content: str) -> None:
    """Write ``content`` to ``path``.

    Behaviour:
      - Creates parent directories as needed.
      - JSON files are written verbatim (with a trailing newline).
      - Markdown files are prefixed with :data:`SCANNER_MARKER`.
      - If the file already exists with the AI-ENRICHED marker in its first
        500 bytes, the write is SKIPPED unless ``--force`` is in effect or
        the path is in :data:`ALWAYS_OVERWRITE` / under ``05_indexes/``.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    file_name = path.name
    is_index = "05_indexes" in path.as_posix() or file_name in ALWAYS_OVERWRITE

    # Incremental protection: respect AI-ENRICHED files unless forced.
    if not _force_overwrite and not is_index and path.exists():
        try:
            existing = path.read_text(encoding="utf-8")[:500]
            if AI_ENRICHED_MARKER in existing:
                print(f"[SKIP] {path.name} — AI-ENRICHED 保护")
                return
        except OSError:
            pass

    if path.suffix == ".json":
        path.write_text(content.rstrip() + "\n", encoding="utf-8")
    else:
        final = SCANNER_MARKER + "\n" + content.rstrip() + "\n"
        path.write_text(final, encoding="utf-8")
