"""Output writers for the BCL.

These functions are the language-agnostic generators that consume FileInfo
records and produce the on-disk BCL tree. Java-specific extras (Dubbo /
Feign / MyBatis / XxlJob) are read via the @property bridges defined on
FileInfo so callers do not need to special-case the legacy fields.

Cross-cutting concern files (mq.md, scheduler.md, …) are NOT generated by
this module. Each plugin registers its cross-cutting contributions with
:mod:`code2wiki.core.cross_cutting`; the orchestrator emits the merged
file once every plugin has finished scanning.
"""

from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path

from code2wiki.core.io import (
    AUXILIARY_DIRS,
    AUXILIARY_SUFFIXES,
    extract_string_values,
    iter_auxiliary_files,
    read_text,
    rel,
    write,
)
from code2wiki.core.markdown import (
    _extract_business_words,
    md_table,
    role_label,
    skill_name_from_project,
)
from code2wiki.core.models import (
    FileInfo,
    JavaFileInfo,
    MyBatisXmlInfo,
    ProjectContext,
)
from code2wiki.core.domain import CLASS_SUFFIXES


def build_keyword_domain_map(top_domains: list[str], grouped: dict[str, list]) -> str:
    """构建需求关键词→域的快速定位表。从 API 路径、类名、MQ Consumer、方法名、class_doc、枚举名中提取。"""
    rows: list[list[str]] = []
    for domain in top_domains[:25]:
        files = grouped.get(domain, [])
        if not files:
            continue
        biz_words: dict[str, int] = {}  # word -> frequency

        def add_word(w: str, weight: int = 1) -> None:
            wl = w.lower().strip()
            if wl and len(wl) > 2:
                biz_words[wl] = biz_words.get(wl, 0) + weight

        # 域名本身（最高权重）
        for part in domain.split("-"):
            add_word(part, 10)

        for f in files:
            # API 路径中的业务词
            for mapping in f.mappings[:5]:
                for seg in mapping.strip("/").split("/"):
                    if seg and seg not in {"<class-level>", "api", "v1", "v2", "admin", "internal"}:
                        add_word(seg, 3)

            # MQ Consumer 类名中的业务词（权重高）
            if f.role == "mq-consumer" and f.class_name:
                for w in _extract_business_words(f.class_name):
                    add_word(w, 4)

            # 定时任务名
            for job in f.xxl_jobs:
                for w in _extract_business_words(job):
                    add_word(w, 3)

            # Service/Controller 的核心方法名
            if f.role in ("controller", "service") and f.public_methods:
                for m in f.public_methods[:5]:
                    for w in _extract_business_words(m["name"]):
                        add_word(w, 2)

            # class_doc 中的关键词
            if f.class_doc:
                for w in re.findall(r"[\u4e00-\u9fff]+", f.class_doc):  # 中文词
                    add_word(w, 3)
                for w in _extract_business_words(f.class_doc):
                    add_word(w, 1)

            # 枚举类名中的业务词
            if f.role == "enum" and f.class_name:
                for w in _extract_business_words(f.class_name):
                    add_word(w, 2)

        # 排序取 top keywords
        sorted_kw = sorted(biz_words.items(), key=lambda x: -x[1])
        top_kw = [kw for kw, _ in sorted_kw if kw != domain][:6]

        # 首先阅读的文件
        first_file = ""
        for role_pref in ("controller", "service", "mq-consumer"):
            for f in files:
                if f.role == role_pref and f.class_name:
                    first_file = f.class_name
                    break
            if first_file:
                break

        display_kw = [domain] + top_kw[:4]
        rows.append([", ".join(display_kw), domain, first_file or "-"])
    if not rows:
        return ""
    return md_table(["需求关键词", "定位域", "首先阅读"], rows, 25)


def build_mermaid_domain_graph(java_infos: list, top_domains: list[str]) -> str:
    """构建 Mermaid 域间依赖图。"""
    # 收集域间调用关系
    edges: dict[tuple[str, str], set[str]] = defaultdict(set)
    # 建立类名→域的映射
    class_to_domain: dict[str, str] = {}
    for info in java_infos:
        if info.class_name and info.domain in top_domains:
            class_to_domain[info.class_name] = info.domain
            # 也映射小写首字母版本（变量名常用）
            lower_first = info.class_name[0].lower() + info.class_name[1:]
            class_to_domain[lower_first] = info.domain

    for info in java_infos:
        if info.domain not in top_domains or info.domain == "unknown":
            continue
        for ct in info.call_targets:
            target_cls = ct["target_class"]
            target_domain = class_to_domain.get(target_cls)
            if target_domain and target_domain != info.domain and target_domain in top_domains:
                edges[(info.domain, target_domain)].add(ct["method"])

    if not edges:
        return ""

    # 只保留 top 12 条边，按调用方法数排序
    sorted_edges = sorted(edges.items(), key=lambda x: -len(x[1]))[:12]

    lines = ["```mermaid", "graph LR"]
    for (src, dst), methods in sorted_edges:
        src_id = src.replace("-", "_")
        dst_id = dst.replace("-", "_")
        count = len(methods)
        lines.append(f"  {src_id}[{src}] -->|{count}次调用| {dst_id}[{dst}]")
    lines.append("```")
    return "\n".join(lines)


def generate_root_skill(output: Path, project: Path, top_domains: list[str],
                        java_infos: list | None = None, grouped: dict | None = None) -> None:
    skill_name = skill_name_from_project(project)
    top = "、".join(top_domains[:12]) if top_domains else "候选业务域"

    # 构建需求定位快速通道
    keyword_table = ""
    if grouped:
        keyword_table = build_keyword_domain_map(top_domains, grouped)

    # 构建 Mermaid 域间依赖图
    mermaid_graph = ""
    if java_infos:
        mermaid_graph = build_mermaid_domain_graph(java_infos, top_domains)

    keyword_section = ""
    if keyword_table:
        keyword_section = f"""
## 需求定位快速通道

收到需求后，用需求中的关键词在下表中快速匹配业务域：

{keyword_table}
"""

    mermaid_section = ""
    if mermaid_graph:
        mermaid_section = f"""
## 域间依赖关系

{mermaid_graph}
"""

    write(output / "SKILL.md", f"""---
name: {skill_name}
description: {project.name} 项目的业务上下文 skill。用于让 AI 基于 Business Context Layer 理解该 Java/Spring 后端项目，并在新需求开发、缺陷排查、接口变更、数据库字段变更、MQ/Job 改造、业务流程调整时快速定位业务域、核心入口、数据模型、集成依赖和风险点。候选业务域包括：{top}。
---

# {project.name} Business Context Skill

## 使用目标

使用本 skill 时，先通过业务语义定位需求，再阅读精确代码。不要直接全局搜索后开始改代码；必须先建立"需求 -> 业务域 -> 流程 -> 入口 -> 数据 -> 风险 -> 测试"的链路。
{keyword_section}
## 新需求处理流程

1. 读取 `00_project_overview.md`，了解系统定位、模块、候选业务域和核心风险。
2. **用上面的"需求定位快速通道"或 `05_indexes/business_domain_map.md`** 定位候选业务域。
3. 读取候选业务域的 `01_business_domains/<domain>/skill.md`（每个域最重要的入口文件）。
4. 读取 `call_chains.md` 了解调用关系，再按需深入 `workflows.md`、`concepts.md` 等。
5. 根据映射中的文件路径回到源码阅读。
6. 修改代码前检查权限、事务、幂等、并发、缓存、状态机、外部接口、历史数据兼容和测试影响。
7. 完成需求后更新对应领域文档和相关索引。
{mermaid_section}
## 快速入口

- 项目总览：`00_project_overview.md`
- 业务域地图：`05_indexes/business_domain_map.md`
- 域间调用图：`05_indexes/call_graph.md`
- API 索引：`05_indexes/api_index.md`
- 代码入口索引：`05_indexes/code_entrypoint_index.md`
- Git 活跃度：`05_indexes/git_activity.md`（热点文件、域活跃度、贡献者）
- 可选辅助知识：`06_auxiliary_knowledge/auxiliary_knowledge.md`

## 上下文加载策略（L0/L1/L2）

- **L0**：先加载项目总览、需求定位快速通道、术语表。
- **L1**：只加载命中的业务域 `skill.md` + `call_chains.md`。
- **L2**：再加载该业务域的 workflows/concepts/API/DB/integration/risk/examples。
- **Source**：最后阅读 L2 指向的源码文件。
""")


# ──────────────────────────────────────────────────────────────────────────────
# Generation: Business domain docs (v2 — 有实质内容)
# ──────────────────────────────────────────────────────────────────────────────

def generate_domain_docs(output: Path, domain: str, files: list[FileInfo], ctx: ProjectContext,
                         mybatis_xmls: list[MyBatisXmlInfo] | None = None) -> None:
    domain_dir = output / "01_business_domains" / domain
    by_role: dict[str, list[FileInfo]] = defaultdict(list)
    for item in files:
        by_role[item.role].append(item)

    # ── skill.md（域入口，最重要的文件） ──────────────────────────────
    controllers = by_role.get("controller", [])
    services = by_role.get("service", [])
    mq_consumers = by_role.get("mq-consumer", [])
    schedulers = by_role.get("scheduler", [])
    entities = by_role.get("entity", [])
    repos = by_role.get("repository", [])
    enums = by_role.get("enum", [])
    ext_clients = by_role.get("external-client", [])
    caches = by_role.get("cache", [])

    # 统计
    role_stats = ", ".join(f"{role_label(r)} {len(fs)}" for r, fs in sorted(by_role.items()) if fs)

    # API 路径
    api_paths = []
    for f in controllers:
        api_paths.extend(f.mappings)
    api_summary = "\n".join(f"- `{p}`" for p in api_paths[:15]) if api_paths else "- 无直接 API 入口"

    # 表名
    all_tables = sorted({t for f in files for t in f.tables})
    table_summary = ", ".join(f"`{t}`" for t in all_tables[:10]) if all_tables else "无直接表注解（可能通过 RPC 访问数据层）"

    # MQ 消费者
    mq_items = []
    for f in mq_consumers:
        mq_items.append(f"- `{f.class_name or f.path}` — {f.class_doc or '需要确认业务含义'}")
    for f in files:
        if f.is_mq_consumer_custom and f.role != "mq-consumer":
            mq_items.append(f"- `{f.class_name or f.path}` (Producer 中包含 MQ Handle 引用)")
    mq_summary = "\n".join(mq_items[:10]) if mq_items else "- 未检测到 MQ 消费者"

    # MQ 生产者
    producer_files = [f for f in files if f.is_mq_producer]
    producer_summary = "\n".join(f"- `{f.class_name}` ({f.path})" for f in producer_files[:5]) if producer_files else "- 未检测到 MQ 发送"

    # 定时任务
    job_items = []
    for f in schedulers:
        job_names = ", ".join(f.xxl_jobs) if f.xxl_jobs else ", ".join(f.scheduled) if f.scheduled else "检测到调度角色"
        job_items.append(f"- `{f.class_name or f.path}`: {job_names}")
    job_summary = "\n".join(job_items[:10]) if job_items else "- 未检测到定时任务"

    # Dubbo RPC 依赖
    dubbo_refs_all = sorted({ref for f in files for ref in f.dubbo_refs})
    dubbo_summary = "\n".join(f"- `{r}`" for r in dubbo_refs_all[:10]) if dubbo_refs_all else ""

    # Feign RPC 依赖
    feign_items = []
    for f in files:
        if f.feign_detail and f.feign_detail.get("service"):
            svc = f.feign_detail["service"]
            path = f.feign_detail.get("path", "")
            path_info = f" path=`{path}`" if path else ""
            feign_items.append(f"- `{f.class_name}` → **{svc}**{path_info}")
    feign_summary = "\n".join(feign_items[:10]) if feign_items else ""

    # 合成 RPC 依赖段落
    rpc_section = ""
    if dubbo_summary or feign_summary:
        if dubbo_summary:
            rpc_section += "### Dubbo RPC\n\n" + dubbo_summary + "\n\n"
        if feign_summary:
            rpc_section += "### Feign HTTP\n\n" + feign_summary + "\n\n"
    else:
        rpc_section = "- 未检测到 RPC 依赖\n"

    # 风险信号
    all_risks = sorted({s for f in files for s in f.risk_signals})
    risk_summary = ", ".join(all_risks) if all_risks else "无明显风险信号"

    # 关键文件
    key_files = sorted(files, key=lambda f: (
        f.role != "controller",
        f.role != "service",
        f.role != "mq-consumer",
        f.role != "scheduler",
        f.path,
    ))[:20]
    key_table = md_table(
        ["角色", "类", "说明", "文件"],
        [[role_label(f.role), f.class_name or "-", f.class_doc or "-", f.path] for f in key_files],
        20,
    )

    write(domain_dir / "skill.md", f"""# {domain} 业务域

## 何时使用

当需求、缺陷或排查涉及以下关键词时使用本域文档：`{domain}`、{', '.join(f'`{p}`' for p in api_paths[:5])}

## 文件统计

{role_stats}，共 {len(files)} 个文件

## API 入口

{api_summary}

## 关联数据表

{table_summary}

## MQ 消费者

{mq_summary}

## MQ 发送

{producer_summary}

## 定时任务

{job_summary}

## RPC 依赖

{rpc_section}
## 风险信号

{risk_summary}

## 核心文件清单

{key_table}

## 修改前检查

- **权限**：检查 Controller 的拦截器、注解和用户上下文
- **事务**：优先阅读带 `@Transactional` 的 Service/Manager
- **幂等**：检查唯一键、业务单号、回调/消息重复消费
- **并发**：检查锁、状态流转、库存/余额/次数类扣减
- **缓存**：检查 Redis、Cache 注解和缓存失效时机
- **兼容性**：检查枚举、状态码、历史数据和外部接口契约
""")

    # ── concepts.md（有数据填充） ──────────────────────────────
    # Entity/DTO 字段
    field_rows = []
    for f in files:
        if f.fields and f.role in ("entity", "dto", "other"):
            for fld in f.fields[:15]:
                field_rows.append([f.class_name or "-", fld["name"], fld["type"], f.path])

    # 枚举值
    enum_rows = []
    for f in files:
        if f.enum_values:
            vals = ", ".join(f.enum_values[:10])
            if len(f.enum_values) > 10:
                vals += f" ... (共{len(f.enum_values)}个)"
            enum_rows.append([f.class_name or "-", vals, f.path])

    concepts_content = f"# {domain} 核心概念\n\n"

    if field_rows:
        concepts_content += "## Entity/DTO 字段\n\n"
        concepts_content += md_table(["类", "字段", "类型", "文件"], field_rows, 60)
        concepts_content += "\n\n"
    else:
        concepts_content += "## Entity/DTO 字段\n\n本域未检测到带字段的 Entity/DTO，可能数据模型在独立的 data 模块中。\n\n"

    if enum_rows:
        concepts_content += "## 枚举/状态值\n\n"
        concepts_content += md_table(["枚举类", "常量值", "文件"], enum_rows, 30)
        concepts_content += "\n\n"

    concepts_content += "## 业务术语映射\n\n"
    concepts_content += "根据代码中的类名推断的候选术语（需人工校准）：\n\n"
    seen_concepts = set()
    for f in files:
        if f.class_name and f.role in ("entity", "dto", "enum", "service"):
            base = f.class_name
            for suffix in CLASS_SUFFIXES:
                if base.endswith(suffix):
                    base = base[:-len(suffix)]
                    break
            if base and base not in seen_concepts and len(base) > 2:
                seen_concepts.add(base)
    for concept in sorted(seen_concepts)[:20]:
        concepts_content += f"- `{concept}` → 需要确认业务含义\n"

    write(domain_dir / "concepts.md", concepts_content)

    # ── api_map.md ──────────────────────────────
    api_rows = []
    for f in controllers:
        mappings = ", ".join(f.mappings) if f.mappings else "-"
        api_rows.append([mappings, f.class_name or "-", f.class_doc or "需要补充", f.path])
    write(domain_dir / "api_map.md", f"# {domain} API Map\n\n"
          + md_table(["接口路径", "Controller", "说明", "文件"], api_rows, 200))

    # ── db_map.md（有数据填充） ──────────────────────────────
    db_rows = []
    for f in files:
        if f.role in ("entity", "repository") or f.tables:
            db_rows.append([", ".join(f.tables) or "-", f.class_name or "-", role_label(f.role), f.path])

    # Entity 字段详情
    entity_field_sections = ""
    for f in files:
        if f.fields and f.role == "entity":
            entity_field_sections += f"\n### {f.class_name} (`{f.path}`)\n\n"
            entity_field_sections += md_table(
                ["字段", "类型"],
                [[fld["name"], fld["type"]] for fld in f.fields[:25]],
            )
            entity_field_sections += "\n"

    db_content = f"# {domain} DB Map\n\n"
    if db_rows:
        db_content += md_table(["表/注解", "类", "角色", "文件"], db_rows, 200) + "\n\n"
    else:
        db_content += "未检测到直接的表注解或 Entity/Mapper。数据访问可能通过 Dubbo RPC 调用独立的 data 模块。\n\n"
        if dubbo_refs_all:
            db_content += "### 通过 RPC 引用的数据服务\n\n"
            for ref in dubbo_refs_all[:15]:
                if "rpc" in ref.lower() or "service" in ref.lower():
                    db_content += f"- `{ref}`\n"
            db_content += "\n"
    if entity_field_sections:
        db_content += "## Entity 字段详情\n" + entity_field_sections

    # MyBatis XML 表信息
    if mybatis_xmls:
        # 按 namespace 中的关键词匹配域
        domain_xmls = []
        for mx in mybatis_xmls:
            ns_lower = mx.namespace.lower()
            # 域名出现在 namespace 中
            if domain.replace("-", "") in ns_lower or domain.replace("-", ".") in ns_lower:
                domain_xmls.append(mx)
            else:
                # 或者 Mapper 类名与域内文件匹配
                ns_class = mx.namespace.split(".")[-1] if "." in mx.namespace else mx.namespace
                for f in files:
                    if f.class_name and f.class_name == ns_class:
                        domain_xmls.append(mx)
                        break
        if domain_xmls:
            db_content += "## MyBatis XML 映射\n\n"
            for mx in domain_xmls[:10]:
                tables_str = ", ".join(f"`{t}`" for t in mx.tables[:8]) if mx.tables else "需确认"
                sql_count = len(mx.sql_ids)
                db_content += f"### `{mx.namespace}` — `{mx.path}`\n\n"
                db_content += f"- 关联表：{tables_str}\n"
                db_content += f"- SQL 操作数：{sql_count}\n"
                if mx.sql_ids:
                    db_content += f"- 操作列表：{', '.join(mx.sql_ids[:8])}"
                    if sql_count > 8:
                        db_content += f" ... (共{sql_count}个)"
                    db_content += "\n"
                db_content += "\n"

    write(domain_dir / "db_map.md", db_content)

    # ── code_entrypoints.md ──────────────────────────────
    entry_rows = [[role_label(f.role), f.class_name or "-", f.class_doc or "-", f.path, ", ".join(f.risk_signals) or "-"]
                  for f in sorted(files, key=lambda x: (x.role, x.path))]
    write(domain_dir / "code_entrypoints.md",
          f"# {domain} Code Entrypoints\n\n"
          + md_table(["角色", "类", "说明", "文件", "风险信号"], entry_rows, 300))

    # ── integration_map.md（增强版） ──────────────────────────────
    integration_rows = []
    for f in files:
        has_integration = (f.mq_listeners or f.scheduled or f.feign_clients or f.dubbo_refs or
                          f.role in {"external-client", "mq-consumer", "scheduler"} or
                          f.is_mq_producer or f.is_mq_consumer_custom)
        if has_integration:
            integration_rows.append([
                f.class_name or "-",
                role_label(f.role),
                "是" if (f.is_mq_consumer_custom or f.mq_listeners) else "-",
                "是" if f.is_mq_producer else "-",
                ", ".join(f.scheduled) or "-",
                ", ".join(f.feign_clients) or "-",
                ", ".join(f.dubbo_refs[:3]) or "-",
                f.path,
            ])
    write(domain_dir / "integration_map.md",
          f"# {domain} Integration Map\n\n"
          + md_table(["类", "角色", "MQ消费", "MQ发送", "定时任务", "Feign", "Dubbo RPC", "文件"],
                     integration_rows, 200))

    # ── workflows.md（基于方法签名的流程线索） ──────────────────────────────
    wf_content = f"# {domain} Workflows\n\n"
    wf_content += "## 基于代码结构推断的流程线索\n\n"
    wf_content += "以下是从 Controller/Service/MQ Consumer 的 public 方法签名中提取的候选流程，需要结合源码确认真实业务语义。\n\n"

    has_methods = False
    for f in sorted(files, key=lambda x: (x.role != "controller", x.role != "service", x.role != "mq-consumer")):
        if f.public_methods:
            has_methods = True
            wf_content += f"### {f.class_name} ({role_label(f.role)}) — `{f.path}`\n\n"
            if f.class_doc:
                wf_content += f"> {f.class_doc}\n\n"
            method_rows = [[m["name"], m["return_type"], m["params"][:100]] for m in f.public_methods[:15]]
            wf_content += md_table(["方法", "返回类型", "参数"], method_rows) + "\n\n"

    if not has_methods:
        wf_content += "未提取到有意义的方法签名，建议直接阅读核心 Service 源码。\n\n"

    wf_content += """## 流程文档模板

对于每个核心流程，建议补充：

- **触发方式**：API/MQ/Job/回调
- **参与角色**：用户/系统/外部服务
- **前置条件**：状态、权限、参数
- **主流程**：步骤 1 → 2 → 3
- **状态变化**：从 X 到 Y
- **数据写入**：哪些表/字段
- **外部调用**：Dubbo/Feign/MQ 发送
- **失败分支**：回滚/补偿/告警
- **幂等与重试**：如何处理重复
"""
    write(domain_dir / "workflows.md", wf_content)

    # ── risk_points.md ──────────────────────────────
    risk_rows = []
    for f in files:
        for signal in f.risk_signals:
            risk_rows.append([signal, f.class_name or "-", f.path, "需要阅读代码确认影响面"])
    risk_content = f"# {domain} Risk Points\n\n"
    if risk_rows:
        risk_content += md_table(["风险类型", "类", "文件", "说明"], risk_rows, 200)
    else:
        risk_content += "未检测到明显风险信号。但仍需人工审查事务、并发、幂等等问题。"
    risk_content += """

## 人工复核重点

- 事务边界是否包含外部调用（Dubbo/Feign/MQ 发送）
- 回调、MQ、Job 是否支持重复执行
- 状态流转是否存在并发覆盖
- 缓存更新和数据库提交是否一致
"""
    write(domain_dir / "risk_points.md", risk_content)

    # ── examples.md（有指导性内容） ──────────────────────────────
    ex_content = f"# {domain} 常见变更指南\n\n"
    ex_content += "## 根据代码结构推断的常见变更场景\n\n"

    if controllers:
        ex_content += "### 新增/修改 API 接口\n\n"
        ex_content += f"- 参考现有 Controller: `{controllers[0].class_name}` (`{controllers[0].path}`)\n"
        if services:
            ex_content += f"- 业务逻辑放入 Service: `{services[0].class_name}` (`{services[0].path}`)\n"
        ex_content += "- 复用现有 DTO、校验、权限和异常处理风格\n\n"

    if mq_consumers:
        ex_content += "### 新增 MQ 消费者\n\n"
        ex_content += f"- 参考现有 Consumer: `{mq_consumers[0].class_name}` (`{mq_consumers[0].path}`)\n"
        if ctx.has_rocketmq:
            ex_content += "- 实现 `RocketMqHandle` 接口\n"
            ex_content += "- 在 `RocketMqHandleFactory` 中注册 Tag 路由\n"
            ex_content += "- 在 Tag 枚举中新增常量\n"
        ex_content += "- 设计幂等键和失败补偿策略\n\n"

    if schedulers:
        ex_content += "### 新增定时任务\n\n"
        ex_content += f"- 参考现有 Job: `{schedulers[0].class_name}` (`{schedulers[0].path}`)\n"
        if ctx.has_xxljob:
            ex_content += "- 使用 `@XxlJob` 注解，在 XxlJob Admin 注册任务\n"
        ex_content += "\n"

    if entities or repos:
        ex_content += "### 新增/修改数据字段\n\n"
        if entities:
            ex_content += f"- 修改 Entity: `{entities[0].class_name}` (`{entities[0].path}`)\n"
        if repos:
            ex_content += f"- 检查 Mapper/Repository: `{repos[0].class_name}` (`{repos[0].path}`)\n"
        ex_content += "- 处理历史数据默认值和兼容性\n\n"

    ex_content += """## 典型需求记录模板

每次完成需求后建议在此补充：

- **需求**：
- **涉及业务概念**：
- **修改的文件**：
- **风险点**：
- **测试建议**：
"""
    write(domain_dir / "examples.md", ex_content)

    # ── call_chains.md（v3 静态调用链） ──────────────────────────────
    cc_content = f"# {domain} 调用链\n\n"
    cc_content += "以下是从代码中静态提取的 Service/RPC/MQ 调用关系，供 AI 富化流程图时参考。\n\n"

    # 按调用方分组
    has_chains = False
    for f in sorted(files, key=lambda x: (x.role != "controller", x.role != "service", x.path)):
        if not f.call_targets:
            continue
        has_chains = True
        cc_content += f"### {f.class_name} ({role_label(f.role)})\n\n"
        chain_rows = []
        for ct in f.call_targets:
            # 推断调用类型
            target = ct["target_class"]
            call_type = "内部调用"
            if "RpcService" in target or "Rpc" in target:
                call_type = "Dubbo RPC"
            elif "Producer" in target or "Sender" in target:
                call_type = "MQ 发送"
            elif "Client" in target:
                call_type = "外部 HTTP"
            elif "Mapper" in target or "Repository" in target:
                call_type = "数据访问"
            elif "Cache" in target:
                call_type = "缓存操作"
            chain_rows.append([ct["target_class"], ct["method"], call_type])
        cc_content += md_table(["被调用类", "方法", "类型"], chain_rows) + "\n\n"

    if not has_chains:
        cc_content += "未提取到有意义的调用链。\n"

    write(domain_dir / "call_chains.md", cc_content)


# ──────────────────────────────────────────────────────────────────────────────
# Generation: Cross-cutting docs (v2 — 有叙述结构)
# ──────────────────────────────────────────────────────────────────────────────

def generate_business_domain_map(output: Path, domain_counter: Counter[str], grouped: dict[str, list[FileInfo]]) -> None:
    rows = []
    for domain, count in domain_counter.most_common(80):
        if domain == "unknown":
            continue
        files = grouped.get(domain, [])
        controllers = [f for f in files if f.role == "controller"]
        mq_files = [f for f in files if f.role == "mq-consumer" or f.is_mq_consumer_custom]
        repos = [f for f in files if f.role == "repository" or f.tables]
        risks = sorted({signal for f in files for signal in f.risk_signals})
        evidence = []
        for bucket in (controllers, mq_files, repos, files):
            for item in bucket:
                if item.class_name:
                    evidence.append(f"{item.class_name} ({item.path})")
                if len(evidence) >= 3:
                    break
            if len(evidence) >= 3:
                break
        rows.append([
            domain, str(count),
            ", ".join(sorted({f.role for f in files})) or "-",
            "; ".join(evidence) or "需要从索引继续确认",
            ", ".join(risks) or "-",
        ])
    write(output / "05_indexes" / "business_domain_map.md", f"""# Business Domain Map

本文件是自动生成的业务域候选地图。用于帮助 AI 从新需求定位候选业务域。

## 使用方式

1. 从需求中提取业务名词、动作、状态、接口、表、消息、Job 名称
2. 在下表中寻找最接近的业务域
3. 读取 `01_business_domains/<业务域>/skill.md`

{md_table(["候选业务域", "文件数", "角色覆盖", "证据入口", "风险信号"], rows, 80)}
""")


def generate_playbooks(output: Path) -> None:
    playbooks = {
        "locate_business_domain.md": "# 定位业务域\n\n1. 从需求中提取业务名词、状态、动作、接口、表名。\n2. 搜索 `01_business_domains/*/skill.md` 和 `04_glossary/business_terms.md`。\n3. 命中多个域时，优先选择拥有 API/表/MQ 直接入口的域。\n4. 加载该域的 `skill.md`，再按需深入 L2 文档。\n5. 再阅读精确源代码。\n",
        "modify_existing_flow.md": "# 修改已有流程\n\n1. 定位业务域和流程。\n2. 阅读 `workflows.md` 中的方法签名线索。\n3. 沿 Controller/MQ/Job -> Service -> Manager -> Repository 阅读源码。\n4. 检查事务、幂等、权限、缓存、并发、兼容性。\n5. 修改代码并补充测试。\n6. 更新 BCL 的 workflows/risk/examples。\n",
        "add_new_api.md": "# 新增 API\n\n1. 确认属于哪个业务域。\n2. 参考该域已有 Controller 的风格。\n3. Controller 只做协议层转换，业务逻辑放 Service/Manager。\n4. 补充 API 索引和领域 api_map。\n",
        "add_db_field.md": "# 新增数据字段\n\n1. 确认字段业务含义和默认值。\n2. 检查 Entity/DTO/Mapper/XML/转换器/导入导出/缓存。\n3. 处理历史数据和兼容性。\n4. 补充 db_map 和风险说明。\n",
        "add_mq_consumer.md": "# 新增 MQ 消费者\n\n1. 参考 `02_cross_cutting/mq.md` 了解本项目的 MQ 架构。\n2. 实现对应的 Handle 接口，在 Factory 中注册 Tag。\n3. 设计幂等键和失败补偿。\n4. 避免在消费线程中执行不可控长事务。\n5. 补充 integration_map 和测试。\n",
        "troubleshoot_bug.md": "# 排查 Bug\n\n1. 从用户现象映射到业务域。\n2. 查 API/MQ/Job 入口和最近变更。\n3. 检查状态、事务、缓存、重复请求、异步延迟。\n4. 用测试复现后修复。\n5. 把根因沉淀到 examples/risk_points。\n",
    }
    for file_name, content in playbooks.items():
        write(output / "03_development_playbooks" / file_name, content)


def extract_auxiliary_summary(path: Path, root: Path) -> dict[str, str]:
    text = read_text(path, limit=16_000)
    title, description = "", ""
    headings = []
    for line in text.splitlines()[:240]:
        stripped = line.strip()
        if not title and stripped.startswith("#"):
            title = stripped.lstrip("#").strip()
        if stripped.startswith("description:") and not description:
            description = stripped.split(":", 1)[1].strip().strip("|").strip()
        if stripped.startswith("#"):
            headings.append(stripped[:120])
        if len(headings) >= 8:
            break
    return {
        "path": rel(path, root),
        "source": path.parts[len(root.parts)] if len(path.parts) > len(root.parts) else path.parts[0],
        "title": title or path.stem,
        "description": description,
        "headings": " / ".join(headings),
    }


def generate_auxiliary_knowledge(output: Path, project: Path, aux_items: list[dict[str, str]]) -> None:
    if not aux_items:
        write(output / "06_auxiliary_knowledge" / "auxiliary_knowledge.md",
              "# Auxiliary Knowledge\n\n未发现 `.claude`、`.cursor`、`.agents` 等外挂人工知识库。\n"
              "本 BCL 完全基于项目源码、配置等一手材料生成。\n")
        return
    rows = [[item["source"], item["title"], item["path"], item["description"] or item["headings"] or "-"]
            for item in aux_items]
    write(output / "06_auxiliary_knowledge" / "auxiliary_knowledge.md", f"""# Auxiliary Knowledge

本文件汇总 `.claude`、`.cursor`、`.agents` 等外挂人工知识库中的可选信号。

## 使用原则

- 这些内容可以帮助理解业务命名、历史经验和人工沉淀
- 代码、配置、Mapper/XML、测试仍然是事实来源
- 如果辅助知识与代码证据冲突，以代码证据为准

{md_table(["来源", "标题", "文件", "摘要"], rows, 300)}
""")


# ──────────────────────────────────────────────────────────────────────────────
